server:
  port: 8333

spring:
  application:
    name: zuul-proxy
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'

debug:
  true
