spring:
  application:
    name: provider
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
    prefer-ip-address: true
    metadata-map:
      app: Shit
      sign: Holy Shit!
debug: true
management:
  endpoints:
    web:
      exposure:
        include: '*'